name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: rustup install stable
    - name: Build Core
      run: cd core && cargo build
    - name: Test Core
      run: cd core && cargo test
    - name: Build CLI
      run: cd cli && cargo build
